<!doctype html>
<html lang="en">
        <!---head codes for css, bootstrap-->
        @include('frontend.partials.frontendhead')
    <body>
        <!---header code -->
        @include('frontend.partials.frontendheader')

     <!---main body-->

        <main>
                <div class="container-fluid cen-page-header">
                <div class="container">
                    <div class="row">
                    <div class="page-header">
                        <h1>Journals by Category</h1>
                    </div>
                    </div>
                </div>
                </div>

                <div class="container-fluid">
                <div class="container">
                <div class="row my-3">
                    <span><a href="#" class="cen-breadcrumbs"> Home</a>&nbsp;»
                            <a href="#" class="cen-breadcrumbs">Journals</a>&nbsp;»&nbsp;
                            <a href="#" class="cen-breadcrumbs">By Category</a></span>
                </div>
                </div>
                </div>

                <div class="container-fluid">
                <div class="container">
                    <div class="row my-5">
                        <h2>Partner Journals by Category </h2>
                    </div>

                    <div class="cen-about">
                        <div class="row">
                                <h5 class="text-danger fw-bold">Subtitle</h5>
                        </div>

                        <div class="row my-2">
                            <p>
                            Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. </p>
                            <div class="m-4">
                            <ul>
                                <li><a href="#">Category (1)</a></li>
                                <li><a href="#">Category (2)</a></li>
                                <li><a href="#">Category (3)</a></li>
                            </ul>
                            </div>
                        </div>

                        </div>

                    </div>
                </div>



<!-- Saved in parser cache with key enwiki:pcache:idhash:957318-0!canonical and timestamp 20240909123729 and revision id 1229034112. Rendering was triggered because: page-view
 -->
 </div><div class="mw-category-generated" lang="en" dir="ltr"><div id="mw-subcategories">
<h2>Subcategories</h2>
<p>This category has the following 69 subcategories, out of 69 total.
</p><div lang="en" dir="ltr" class="mw-content-ltr"><div class="mw-category mw-category-columns"><div class="mw-category-group"><h3>*</h3>
<ul><li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Medical_journal_cover_images" title="Category:Medical journal cover images">Medical journal cover images</a>&lrm; <span title="Contains 0 subcategories, 0 pages, and 195 files" dir="ltr">(195 F)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li></ul></div><div class="mw-category-group"><h3>+</h3>
<ul><li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeBullet"><a class="CategoryTreeToggle CategoryTreeToggleHandlerAttached" data-ct-title="Medical_journal_editors" aria-expanded="false" href="#" role="button" title="expand"></a> </span> <a href="/wiki/Category:Medical_journal_editors" title="Category:Medical journal editors">Medical journal editors</a>&lrm; <span title="Contains 8 subcategories, 214 pages, and 0 files" dir="ltr">(8 C, 214 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li></ul></div><div class="mw-category-group"><h3>A</h3>
<ul><li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeBullet"><a class="CategoryTreeToggle CategoryTreeToggleHandlerAttached" data-ct-title="Alternative_and_traditional_medicine_journals" aria-expanded="false" href="#" role="button" title="expand"></a> </span> <a href="/wiki/Category:Alternative_and_traditional_medicine_journals" title="Category:Alternative and traditional medicine journals">Alternative and traditional medicine journals</a>&lrm; <span title="Contains 1 subcategory, 36 pages, and 0 files" dir="ltr">(1 C, 36 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Anatomy_journals" title="Category:Anatomy journals">Anatomy journals</a>&lrm; <span title="Contains 0 subcategories, 13 pages, and 0 files" dir="ltr">(13 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Andrology_journals" title="Category:Andrology journals">Andrology journals</a>&lrm; <span title="Contains 0 subcategories, 4 pages, and 0 files" dir="ltr">(4 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Anesthesiology_and_palliative_medicine_journals" title="Category:Anesthesiology and palliative medicine journals">Anesthesiology and palliative medicine journals</a>&lrm; <span title="Contains 0 subcategories, 34 pages, and 0 files" dir="ltr">(34 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Audiology_journals" title="Category:Audiology journals">Audiology journals</a>&lrm; <span title="Contains 0 subcategories, 13 pages, and 0 files" dir="ltr">(13 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li></ul></div><div class="mw-category-group"><h3>B</h3>
<ul><li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Behavioral_medicine_journals" title="Category:Behavioral medicine journals">Behavioral medicine journals</a>&lrm; <span title="Contains 0 subcategories, 5 pages, and 0 files" dir="ltr">(5 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Bioethics_journals" title="Category:Bioethics journals">Bioethics journals</a>&lrm; <span title="Contains 0 subcategories, 26 pages, and 0 files" dir="ltr">(26 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Biomedical_engineering_journals" title="Category:Biomedical engineering journals">Biomedical engineering journals</a>&lrm; <span title="Contains 0 subcategories, 21 pages, and 0 files" dir="ltr">(21 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Biomedical_informatics_journals" title="Category:Biomedical informatics journals">Biomedical informatics journals</a>&lrm; <span title="Contains 0 subcategories, 23 pages, and 0 files" dir="ltr">(23 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Biostatistics_journals" title="Category:Biostatistics journals">Biostatistics journals</a>&lrm; <span title="Contains 0 subcategories, 8 pages, and 0 files" dir="ltr">(8 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li></ul></div><div class="mw-category-group"><h3>C</h3>
<ul><li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeBullet"><a class="CategoryTreeToggle CategoryTreeToggleHandlerAttached" data-ct-title="Cardiology_journals" aria-expanded="false" href="#" role="button" title="expand"></a> </span> <a href="/wiki/Category:Cardiology_journals" title="Category:Cardiology journals">Cardiology journals</a>&lrm; <span title="Contains 4 subcategories, 78 pages, and 0 files" dir="ltr">(4 C, 78 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Case_report_journals" title="Category:Case report journals">Case report journals</a>&lrm; <span title="Contains 0 subcategories, 58 pages, and 0 files" dir="ltr">(58 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Clinical_practice_journals" title="Category:Clinical practice journals">Clinical practice journals</a>&lrm; <span title="Contains 0 subcategories, 4 pages, and 0 files" dir="ltr">(4 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li></ul></div><div class="mw-category-group"><h3>D</h3>
<ul><li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Dentistry_journals" title="Category:Dentistry journals">Dentistry journals</a>&lrm; <span title="Contains 0 subcategories, 40 pages, and 0 files" dir="ltr">(40 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Dermatology_journals" title="Category:Dermatology journals">Dermatology journals</a>&lrm; <span title="Contains 0 subcategories, 33 pages, and 0 files" dir="ltr">(33 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li></ul></div><div class="mw-category-group"><h3>E</h3>
<ul><li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeBullet"><a class="CategoryTreeToggle CategoryTreeToggleHandlerAttached" data-ct-title="Emergency_medicine_journals" aria-expanded="false" href="#" role="button" title="expand"></a> </span> <a href="/wiki/Category:Emergency_medicine_journals" title="Category:Emergency medicine journals">Emergency medicine journals</a>&lrm; <span title="Contains 2 subcategories, 30 pages, and 0 files" dir="ltr">(2 C, 30 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeBullet"><a class="CategoryTreeToggle CategoryTreeToggleHandlerAttached" data-ct-title="Endocrinology_journals" aria-expanded="false" href="#" role="button" title="expand"></a> </span> <a href="/wiki/Category:Endocrinology_journals" title="Category:Endocrinology journals">Endocrinology journals</a>&lrm; <span title="Contains 1 subcategory, 49 pages, and 0 files" dir="ltr">(1 C, 49 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Epidemiology_journals" title="Category:Epidemiology journals">Epidemiology journals</a>&lrm; <span title="Contains 0 subcategories, 31 pages, and 0 files" dir="ltr">(31 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li></ul></div><div class="mw-category-group"><h3>F</h3>
<ul><li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Family_medicine_journals" title="Category:Family medicine journals">Family medicine journals</a>&lrm; <span title="Contains 0 subcategories, 8 pages, and 0 files" dir="ltr">(8 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Federation_of_European_Microbiological_Societies_academic_journals" title="Category:Federation of European Microbiological Societies academic journals">Federation of European Microbiological Societies academic journals</a>&lrm; <span title="Contains 0 subcategories, 7 pages, and 0 files" dir="ltr">(7 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li></ul></div><div class="mw-category-group"><h3>G</h3>
<ul><li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Gastroenterology_and_hepatology_journals" title="Category:Gastroenterology and hepatology journals">Gastroenterology and hepatology journals</a>&lrm; <span title="Contains 0 subcategories, 30 pages, and 0 files" dir="ltr">(30 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeBullet"><a class="CategoryTreeToggle CategoryTreeToggleHandlerAttached" data-ct-title="General_medical_journals" aria-expanded="false" href="#" role="button" title="expand"></a> </span> <a href="/wiki/Category:General_medical_journals" title="Category:General medical journals">General medical journals</a>&lrm; <span title="Contains 1 subcategory, 241 pages, and 0 files" dir="ltr">(1 C, 241 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeBullet"><a class="CategoryTreeToggle CategoryTreeToggleHandlerAttached" data-ct-title="Gerontology_journals" aria-expanded="false" href="#" role="button" title="expand"></a> </span> <a href="/wiki/Category:Gerontology_journals" title="Category:Gerontology journals">Gerontology journals</a>&lrm; <span title="Contains 2 subcategories, 41 pages, and 0 files" dir="ltr">(2 C, 41 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li></ul></div><div class="mw-category-group"><h3>H</h3>
<ul><li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Hematology_journals" title="Category:Hematology journals">Hematology journals</a>&lrm; <span title="Contains 0 subcategories, 24 pages, and 0 files" dir="ltr">(24 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:History_of_medicine_journals" title="Category:History of medicine journals">History of medicine journals</a>&lrm; <span title="Contains 0 subcategories, 15 pages, and 0 files" dir="ltr">(15 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li></ul></div><div class="mw-category-group"><h3>I</h3>
<ul><li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeBullet"><a class="CategoryTreeToggle CategoryTreeToggleHandlerAttached" data-ct-title="Immunology_journals" aria-expanded="false" href="#" role="button" title="expand"></a> </span> <a href="/wiki/Category:Immunology_journals" title="Category:Immunology journals">Immunology journals</a>&lrm; <span title="Contains 3 subcategories, 60 pages, and 0 files" dir="ltr">(3 C, 60 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Internal_medicine_journals" title="Category:Internal medicine journals">Internal medicine journals</a>&lrm; <span title="Contains 0 subcategories, 11 pages, and 0 files" dir="ltr">(11 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li></ul></div><div class="mw-category-group"><h3>L</h3>
<ul><li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Laboratory_medicine_journals" title="Category:Laboratory medicine journals">Laboratory medicine journals</a>&lrm; <span title="Contains 0 subcategories, 12 pages, and 0 files" dir="ltr">(12 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li></ul></div><div class="mw-category-group"><h3>M</h3>
<ul><li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Medical_genetics_journals" title="Category:Medical genetics journals">Medical genetics journals</a>&lrm; <span title="Contains 0 subcategories, 24 pages, and 0 files" dir="ltr">(24 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Medical_physics_journals" title="Category:Medical physics journals">Medical physics journals</a>&lrm; <span title="Contains 0 subcategories, 8 pages, and 0 files" dir="ltr">(8 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Medical_statistics_journals" title="Category:Medical statistics journals">Medical statistics journals</a>&lrm; <span title="Contains 0 subcategories, 1 page, and 0 files" dir="ltr">(1 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Medicinal_chemistry_journals" title="Category:Medicinal chemistry journals">Medicinal chemistry journals</a>&lrm; <span title="Contains 0 subcategories, 21 pages, and 0 files" dir="ltr">(21 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeBullet"><a class="CategoryTreeToggle CategoryTreeToggleHandlerAttached" data-ct-title="Microbiology_journals" aria-expanded="false" href="#" role="button" title="expand"></a> </span> <a href="/wiki/Category:Microbiology_journals" title="Category:Microbiology journals">Microbiology journals</a>&lrm; <span title="Contains 6 subcategories, 94 pages, and 0 files" dir="ltr">(6 C, 94 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li></ul></div><div class="mw-category-group"><h3>N</h3>
<ul><li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Nanomedicine_journals" title="Category:Nanomedicine journals">Nanomedicine journals</a>&lrm; <span title="Contains 0 subcategories, 6 pages, and 0 files" dir="ltr">(6 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Nephrology_journals" title="Category:Nephrology journals">Nephrology journals</a>&lrm; <span title="Contains 0 subcategories, 10 pages, and 0 files" dir="ltr">(10 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeBullet"><a class="CategoryTreeToggle CategoryTreeToggleHandlerAttached" data-ct-title="Neurology_journals" aria-expanded="false" href="#" role="button" title="expand"></a> </span> <a href="/wiki/Category:Neurology_journals" title="Category:Neurology journals">Neurology journals</a>&lrm; <span title="Contains 4 subcategories, 95 pages, and 0 files" dir="ltr">(4 C, 95 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Neurosurgery_journals" title="Category:Neurosurgery journals">Neurosurgery journals</a>&lrm; <span title="Contains 0 subcategories, 9 pages, and 0 files" dir="ltr">(9 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Nutrition_and_dietetics_journals" title="Category:Nutrition and dietetics journals">Nutrition and dietetics journals</a>&lrm; <span title="Contains 0 subcategories, 41 pages, and 0 files" dir="ltr">(41 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li></ul></div><div class="mw-category-group"><h3>O</h3>
<ul><li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeBullet"><a class="CategoryTreeToggle CategoryTreeToggleHandlerAttached" data-ct-title="Obstetrics_and_gynaecology_journals" aria-expanded="false" href="#" role="button" title="expand"></a> </span> <a href="/wiki/Category:Obstetrics_and_gynaecology_journals" title="Category:Obstetrics and gynaecology journals">Obstetrics and gynaecology journals</a>&lrm; <span title="Contains 2 subcategories, 40 pages, and 0 files" dir="ltr">(2 C, 40 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Occupational_safety_and_health_journals" title="Category:Occupational safety and health journals">Occupational safety and health journals</a>&lrm; <span title="Contains 0 subcategories, 26 pages, and 0 files" dir="ltr">(26 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeBullet"><a class="CategoryTreeToggle CategoryTreeToggleHandlerAttached" data-ct-title="Oncology_journals" aria-expanded="false" href="#" role="button" title="expand"></a> </span> <a href="/wiki/Category:Oncology_journals" title="Category:Oncology journals">Oncology journals</a>&lrm; <span title="Contains 2 subcategories, 130 pages, and 0 files" dir="ltr">(2 C, 130 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Ophthalmology_journals" title="Category:Ophthalmology journals">Ophthalmology journals</a>&lrm; <span title="Contains 0 subcategories, 33 pages, and 0 files" dir="ltr">(33 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeBullet"><a class="CategoryTreeToggle CategoryTreeToggleHandlerAttached" data-ct-title="Orthopedics_journals" aria-expanded="false" href="#" role="button" title="expand"></a> </span> <a href="/wiki/Category:Orthopedics_journals" title="Category:Orthopedics journals">Orthopedics journals</a>&lrm; <span title="Contains 1 subcategory, 36 pages, and 0 files" dir="ltr">(1 C, 36 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Otorhinolaryngology_journals" title="Category:Otorhinolaryngology journals">Otorhinolaryngology journals</a>&lrm; <span title="Contains 0 subcategories, 11 pages, and 0 files" dir="ltr">(11 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li></ul></div><div class="mw-category-group"><h3>P</h3>
<ul><li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Parasitology_journals" title="Category:Parasitology journals">Parasitology journals</a>&lrm; <span title="Contains 0 subcategories, 15 pages, and 0 files" dir="ltr">(15 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Pathology_journals" title="Category:Pathology journals">Pathology journals</a>&lrm; <span title="Contains 0 subcategories, 25 pages, and 0 files" dir="ltr">(25 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeBullet"><a class="CategoryTreeToggle CategoryTreeToggleHandlerAttached" data-ct-title="Pediatrics_journals" aria-expanded="false" href="#" role="button" title="expand"></a> </span> <a href="/wiki/Category:Pediatrics_journals" title="Category:Pediatrics journals">Pediatrics journals</a>&lrm; <span title="Contains 3 subcategories, 66 pages, and 0 files" dir="ltr">(3 C, 66 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeBullet"><a class="CategoryTreeToggle CategoryTreeToggleHandlerAttached" data-ct-title="Pharmacology_journals" aria-expanded="false" href="#" role="button" title="expand"></a> </span> <a href="/wiki/Category:Pharmacology_journals" title="Category:Pharmacology journals">Pharmacology journals</a>&lrm; <span title="Contains 2 subcategories, 178 pages, and 0 files" dir="ltr">(2 C, 178 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Physical_medicine_and_rehabilitation_journals" title="Category:Physical medicine and rehabilitation journals">Physical medicine and rehabilitation journals</a>&lrm; <span title="Contains 0 subcategories, 5 pages, and 0 files" dir="ltr">(5 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Physiology_journals" title="Category:Physiology journals">Physiology journals</a>&lrm; <span title="Contains 0 subcategories, 41 pages, and 0 files" dir="ltr">(41 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeBullet"><a class="CategoryTreeToggle CategoryTreeToggleHandlerAttached" data-ct-title="Preventive_medicine_journals" aria-expanded="false" href="#" role="button" title="expand"></a> </span> <a href="/wiki/Category:Preventive_medicine_journals" title="Category:Preventive medicine journals">Preventive medicine journals</a>&lrm; <span title="Contains 1 subcategory, 6 pages, and 0 files" dir="ltr">(1 C, 6 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeBullet"><a class="CategoryTreeToggle CategoryTreeToggleHandlerAttached" data-ct-title="Psychiatry_journals" aria-expanded="false" href="#" role="button" title="expand"></a> </span> <a href="/wiki/Category:Psychiatry_journals" title="Category:Psychiatry journals">Psychiatry journals</a>&lrm; <span title="Contains 8 subcategories, 118 pages, and 0 files" dir="ltr">(8 C, 118 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Pulmonology_journals" title="Category:Pulmonology journals">Pulmonology journals</a>&lrm; <span title="Contains 0 subcategories, 30 pages, and 0 files" dir="ltr">(30 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li></ul></div><div class="mw-category-group"><h3>R</h3>
<ul><li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Radiology_and_medical_imaging_journals" title="Category:Radiology and medical imaging journals">Radiology and medical imaging journals</a>&lrm; <span title="Contains 0 subcategories, 52 pages, and 0 files" dir="ltr">(52 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Regenerative_medicine_journals" title="Category:Regenerative medicine journals">Regenerative medicine journals</a>&lrm; <span title="Contains 0 subcategories, 8 pages, and 0 files" dir="ltr">(8 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeBullet"><a class="CategoryTreeToggle CategoryTreeToggleHandlerAttached" data-ct-title="Rehabilitation_medicine_journals" aria-expanded="false" href="#" role="button" title="expand"></a> </span> <a href="/wiki/Category:Rehabilitation_medicine_journals" title="Category:Rehabilitation medicine journals">Rehabilitation medicine journals</a>&lrm; <span title="Contains 3 subcategories, 10 pages, and 0 files" dir="ltr">(3 C, 10 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Reproductive_health_journals" title="Category:Reproductive health journals">Reproductive health journals</a>&lrm; <span title="Contains 0 subcategories, 10 pages, and 0 files" dir="ltr">(10 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Rheumatology_journals" title="Category:Rheumatology journals">Rheumatology journals</a>&lrm; <span title="Contains 0 subcategories, 15 pages, and 0 files" dir="ltr">(15 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li></ul></div><div class="mw-category-group"><h3>S</h3>
<ul><li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeBullet"><a class="CategoryTreeToggle CategoryTreeToggleHandlerAttached" data-ct-title="Sexology_journals" aria-expanded="false" href="#" role="button" title="expand"></a> </span> <a href="/wiki/Category:Sexology_journals" title="Category:Sexology journals">Sexology journals</a>&lrm; <span title="Contains 1 subcategory, 43 pages, and 0 files" dir="ltr">(1 C, 43 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Sports_medicine_journals" title="Category:Sports medicine journals">Sports medicine journals</a>&lrm; <span title="Contains 0 subcategories, 13 pages, and 0 files" dir="ltr">(13 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeBullet"><a class="CategoryTreeToggle CategoryTreeToggleHandlerAttached" data-ct-title="Surgery_journals" aria-expanded="false" href="#" role="button" title="expand"></a> </span> <a href="/wiki/Category:Surgery_journals" title="Category:Surgery journals">Surgery journals</a>&lrm; <span title="Contains 3 subcategories, 78 pages, and 0 files" dir="ltr">(3 C, 78 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li></ul></div><div class="mw-category-group"><h3>T</h3>
<ul><li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Tobacco_control_journals" title="Category:Tobacco control journals">Tobacco control journals</a>&lrm; <span title="Contains 0 subcategories, 3 pages, and 0 files" dir="ltr">(3 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Toxicology_journals" title="Category:Toxicology journals">Toxicology journals</a>&lrm; <span title="Contains 0 subcategories, 54 pages, and 0 files" dir="ltr">(54 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li>
<li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Tropical_medicine_and_hygiene_journals" title="Category:Tropical medicine and hygiene journals">Tropical medicine and hygiene journals</a>&lrm; <span title="Contains 0 subcategories, 7 pages, and 0 files" dir="ltr">(7 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li></ul></div><div class="mw-category-group"><h3>U</h3>
<ul><li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Urology_journals" title="Category:Urology journals">Urology journals</a>&lrm; <span title="Contains 0 subcategories, 13 pages, and 0 files" dir="ltr">(13 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li></ul></div><div class="mw-category-group"><h3>V</h3>
<ul><li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeEmptyBullet"></span> <a href="/wiki/Category:Veterinary_medicine_journals" title="Category:Veterinary medicine journals">Veterinary medicine journals</a>&lrm; <span title="Contains 0 subcategories, 22 pages, and 0 files" dir="ltr">(22 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li></ul></div><div class="mw-category-group"><h3>Σ</h3>
<ul><li><div class="CategoryTreeSection"><div class="CategoryTreeItem"><span class="CategoryTreeBullet"><a class="CategoryTreeToggle CategoryTreeToggleHandlerAttached" data-ct-title="Medical_journal_stubs" aria-expanded="false" href="#" role="button" title="expand"></a> </span> <a href="/wiki/Category:Medical_journal_stubs" title="Category:Medical journal stubs">Medical journal stubs</a>&lrm; <span title="Contains 11 subcategories, 347 pages, and 0 files" dir="ltr">(11 C, 347 P)</span></div><div class="CategoryTreeChildren" style="display:none"></div></div></li></ul></div></div></div>
</div><div id="mw-pages">
<h2><span class="anchor" id="Pages_in_category"></span>Pages in category "Medical journals"</h2>
<p>The following 2 pages are in this category, out of  2 total. <a href="/wiki/Wikipedia:FAQ/Categorization#Why_might_a_category_list_not_be_up_to_date?" title="Wikipedia:FAQ/Categorization">This list may not reflect recent changes</a>.
</p><div lang="en" dir="ltr" class="mw-content-ltr"><div class="mw-category"><div class="mw-category-group"><h3>&nbsp;</h3>
<ul><li><a href="/wiki/List_of_medical_journals" title="List of medical journals">List of medical journals</a></li>
<li><a href="/wiki/Medical_journal" title="Medical journal">Medical journal</a></li></ul></div></div></div>
</div></div><!--esi <esi:include src="/esitest-fa8a495983347898/content" /> --><noscript><img src="https://login.wikimedia.org/wiki/Special:CentralAutoLogin/start?type=1x1" alt="" width="1" height="1" style="border: none; position: absolute;"></noscript>
<div class="printfooter" data-nosnippet="">Retrieved from "<a dir="ltr" href="https://en.wikipedia.org/w/index.php?title=Category:Medical_journals&amp;oldid=1229034112">https://en.wikipedia.org/w/index.php?title=Category:Medical_journals&amp;oldid=1229034112</a>"</div></div>
					<div id="catlinks" class="catlinks" data-mw="interface"><div id="mw-normal-catlinks" class="mw-normal-catlinks"><a href="/wiki/Help:Category" title="Help:Category">Categories</a>: <ul><li><a href="/wiki/Category:Academic_works_about_medicine" title="Category:Academic works about medicine">Academic works about medicine</a></li><li><a href="/wiki/Category:Medical_research" title="Category:Medical research">Medical research</a></li><li><a href="/wiki/Category:Healthcare_journals" title="Category:Healthcare journals">Healthcare journals</a></li></ul></div><div id="mw-hidden-catlinks" class="mw-hidden-catlinks mw-hidden-cats-ns-shown">Hidden categories: <ul><li><a href="/wiki/Category:Categories_requiring_diffusion" title="Category:Categories requiring diffusion">Categories requiring diffusion</a></li><li><a href="/wiki/Category:Commons_category_link_is_on_Wikidata" title="Category:Commons category link is on Wikidata">Commons category link is on Wikidata</a></li></ul></div></div>
				</div>





            </main>

    <!--footer-->
        @include('frontend.partials.frontendfooter')

  </body>
</html>
