<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     * For ROLES
        * Vice Editor in Chief
        * Associate Editor
        * Managing Editor
        * Editorial Advisory Board
        * Editorial Board Members
        * Editorial Assistant
        * Journal Contact
        * Editor in Chief
     */
    public function up(): void
    {
        Schema::create('users', function (Blueprint $table) {
            $table->id();
            $table->string('org_id')->nullable(); // for authors
            $table->string('title')->nullable();
            $table->string('fname')->nullable();
            $table->string('lname')->nullable();
            $table->string('mname')->nullable();
            $table->string('username')->nullable();
            $table->string('email')->nullable();//->unique();
            $table->timestamp('email_verified_at')->nullable();
            $table->string('password')->nullable(); // autogenerated for contacts.
            $table->text('address')->nullable();
            $table->string('role')->nullable(); // admin,author reveiwer, contact
            $table->string('user_type')->nullable(); // contact, standard(able to login)
            $table->string('status')->nullable(); //active, inactive
            $table->rememberToken();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('users');
    }
};
