<?php

return array(

    'sub_reviewer' => array(
        "Reviewing Essentials",
        "Assessment Techniques",
        "Feedback Strategies",
        "Ethics and Integrity",
        "Other Useful Educational Resources",
        "Useful Organization"
    ),

    'sub_author' => array(
        "Other Useful Educational Resources",
        "Manuscript Preparation",
        "Submission Guidelines",
        "Ethical Considerations",
        "Data Reporting"
    ),

    'sub_editor' => array(
        "Peer Review Processes",
        "Editorial Practices",
        "Other Useful Educational Resources",
        "Publication Ethics"
    ),
    'sub_researcher' => array(
        "Research Methodologies",
        "Other Useful Educational Resources",
        "Blogs/Report/Articles",
        "Essential Readings",
        "Toolkits"
    ),

    'sub_category' => array(
        "Blogs/Report/Articles",
        "Courses",
        "Essential Readings",
        "Toolkits"
    ),
    'sub_classification' => array(
        "Course",
        "Blog",
        "Guidelines",
        "Report",
        "Education Resource",
        "Webinar",
        "Organization",
        "Journal Article"
    ),

    'page_type' => array(
        "Resource",
        "News",
        "Announcement",
        "Banner"
    ),

    'res_category' => array(
        "Editor",
        "Researcher",
        "Reviewer",
        "Author",
        "Not Applicable"
    ),

    'member_type' => array(
        "Editor in Chief",
        "Associate Editor",
        "Managing Editor",
        "Editorial Assistant"
    ),

    'resource_sources' => array(
        "ACSE",
        "Alan Meier",
        "ALPSP",
        "American Chemical Society (ACS)",
        "American Psychological Association",
        "American Psychological Association (APA)",
        "American Speech-Language-Hearing Association (ASHA)",
        "APAME",
        "BMJ",
        "British Ecological Society",
        "C4DISC",
        "Cambridge University Press",
        "Canadian Science Publishing",
        "CASE",
        "Center for Open Science",
        "Clarivate Web of Science Academy",
        "COCHRANE",
        "Cochrane Library",
        "Committee on Publication Ethics (COPE)",
        "CONSORT",
        "CONSORT Group",
        "COPE",
        "Cosmoderma",
        "Council of Science Editors",
        "DistillerSR Inc.",
        "DOI",
        "Dove Medical Press",
        "EASE",
        "Elsevier",
        "Elsevier Academy",
        "Elsevier Researcher Academy",
        "Emerald Publishing",
        "EQUATOR",
        "EQUATOR Network",
        "European Association of Science Editors",
        "ICJME",
        "ICMJE",
        "Indiana University Bloomington",
        "Indiana University Bloomington Libraries",
        "INSAP",
        "International Congress on Peer Review and Scientific Publication",
        "International Food Information Service (IFIS Publishing)",
        "IOP Publishing",
        "IPA",
        "ISRCTN",
        "Julius Kuhn-Institut (JKI)",
        "Matt Might",
        "Medical University of South Carolina (MUSC) Libraries",
        "MedRxiv",
        "National Library of Medicine",
        "Nature",
        "Nature Chemical Biology",
        "Neurology India",
        "OASPA",
        "Old Dominion University",
        "ORCID",
        "ORI",
        "OUP Blog",
        "Oxford University Press",
        "Oxford University Press (OUP)",
        "PCHRD",
        "PCHRD Publications",
        "Peer Review Congress",
        "Peeref",
        "Physiology Journals",
        "Physiology.org",
        "PKP School",
        "PLOS",
        "PLOS ONE",
        "Publishing Research Consortium",
        "PubMed",
        "Queen's University Library",
        "Research Integrity Journal",
        "SAGE Publications",
        "Scholastica",
        "SCIELO Network",
        "ScienceDirect",
        "Sense about Science",
        "Society for Scholarly Publishing (SSP)",
        "Springer Nature",
        "SSP",
        "STM",
        "Taylor & Francis",
        "The British Medical Journal",
        "The British Medical Journal (BMJ)",
        "The Guardian",
        "University of Chicago Press",
        "University of Kansas Libraries",
        "University of London UK",
        "University of Massachusetts Amherst",
        "University of Toronto Press",
        "University of Toronto Press Journals",
        "Violent Metaphors",
        "Visionlearning",
        "WAME",
        "Web of Science Academy",
        "Wiley",
        "Wiley Researcher Academy",
        "Wiley-Blackwell",
        "Wolters Kluwer",
        "World Health Organization"
    ),
);
